### ISSUE TITLE
Bezier Cuves with Thickness

### ISSUE THREAD

**Issue by ruippgoncalves** [zingl/Bresenham#1]
This only creates a Bezier Curve with 1px thick line, it should allow to create with an unspecified amount as the line plotLineWidth does. Could you please implement it, I've been trying to do that my self but was unsuccessfull.

**Comment by zingl** [comment]
Hi,


There are also plotXXWidth for lines, ellipses and all Beziers for at 
least in javaScript on the scratchpad 
<https://zingl.github.io/canvas.html> if you want to use:

https://zingl.github.io/bresenham.js


Kind reagrs, Alois



Am 28.09.2021 um 15:57 schrieb Rui Gonçalves:

**Comment by ruippgoncalves** [comment]
Thanks, that was what I needed, I was not looking to the scratchpad.
